# -*- coding: utf-8 -*-
"""Migration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fxJK_6vnlrBE8Y8XqcjhDRv7VqLur6Aw
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random

# Define the fish species and other parameters
species_list = ["Salmon", "Tuna", "Turtle", "Shark", "Trout", "Cod", "Mackerel", "Bass", "Swordfish", "Dolphin"]
latitude_range = (30.0, 50.0)  # Approximate latitude range for oceanic and river locations
longitude_range = (-130.0, -110.0)  # Approximate longitude range for oceanic and river locations
temperature_range = (10, 25)  # Water temperature in Celsius
salinity_range = (30, 37)  # Water salinity level (PSU)

# Parameters for synthetic data generation
num_rows = 1000  # Number of rows of data
start_date = datetime(2023, 1, 1)

# Function to randomly generate dates within a year
def random_date(start, end):
    return start + timedelta(days=random.randint(0, (end - start).days))

# Create an empty list to store synthetic data
data = []

# Generate synthetic data
for _ in range(num_rows):
    species = random.choice(species_list)
    latitude = round(np.random.uniform(*latitude_range), 4)
    longitude = round(np.random.uniform(*longitude_range), 4)

    # Random date within 2023
    date = random_date(start_date, start_date + timedelta(days=365)).strftime('%Y-%m-%d')

    # Generate random environmental factors
    water_temperature = round(np.random.uniform(*temperature_range), 1)
    water_salinity = round(np.random.uniform(*salinity_range), 1)

    # Simulate breeding season start and end based on species
    breeding_start = random_date(datetime(2023, 5, 1), datetime(2023, 8, 1)).strftime('%Y-%m-%d')
    breeding_end = (datetime.strptime(breeding_start, '%Y-%m-%d') + timedelta(days=random.randint(30, 90))).strftime('%Y-%m-%d')

    # Append row to data list
    data.append([species, latitude, longitude, date, water_temperature, water_salinity, breeding_start, breeding_end])

# Create DataFrame from generated data
df = pd.DataFrame(data, columns=["Species", "Latitude", "Longitude", "Date", "Water_Temperature", "Water_Salinity", "Breeding_Season_Start", "Breeding_Season_End"])

# Save to CSV
df.to_csv("synthetic_fish_migration_data.csv", index=False)

print("Synthetic fish migration dataset saved as 'synthetic_fish_migration_data.csv'")
print(df.head())  # Preview first few rows of the data